apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{"meta.helm.sh/release-name":"sd","meta.helm.sh/release-namespace":"ordingj"},"creationTimestamp":"2025-11-25T02:25:02Z","generation":2,"labels":{"app.kubernetes.io/instance":"sd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"stable-diffusion","app.kubernetes.io/version":"1.4.0","helm.sh/chart":"stable-diffusion-1.0.6"},"name":"sd-stable-diffusion","namespace":"ordingj","resourceVersion":"11963505892","uid":"5e38ee1f-98ff-4e18-9134-7f5d284bee63"},"spec":{"persistentVolumeClaimRetentionPolicy":{"whenDeleted":"Retain","whenScaled":"Retain"},"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"sd","app.kubernetes.io/name":"stable-diffusion"}},"serviceName":"sd-stable-diffusion","template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"sd","app.kubernetes.io/name":"stable-diffusion"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"sd-stable-diffusion-config"}}],"image":"amithkk/stable-diffusion:latest","imagePullPolicy":"IfNotPresent","name":"stable-diffusion-stable-diffusion","ports":[{"containerPort":7860,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"4","memory":"16Gi","nvidia.com/gpu":"1"},"requests":{"cpu":"2","memory":"8Gi","nvidia.com/gpu":"1"}},"securityContext":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/models","name":"sd-stable-diffusion-model-store"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"args":["-c","set -e\nmkdir -p /models\n\necho \"Downloading Stable Diffusion 1.4...\"\ncurl -L \"https://f004.backblazeb2.com/file/aai-blog-files/sd-v1-4.ckpt\" -o /models/model.ckpt\n\necho \"Downloading GFPGAN...\"\ncurl -L \"https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth\" -o /models/GFPGANv1.3.pth\n\necho \"Downloading RealESRGAN models...\"\ncurl -L \"https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth\" -o /models/RealESRGAN_x4plus.pth\ncurl -L \"https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth\" -o /models/RealESRGAN_x4plus_anime_6B.pth\n"],"command":["/bin/sh"],"image":"curlimages/curl:8.10.1","name":"ensure-stable-models","volumeMounts":[{"mountPath":"/models","name":"sd-stable-diffusion-model-store"}]}],"nodeSelector":{"nvidia.com/gpu.present":"true"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"sd-stable-diffusion","serviceAccountName":"sd-stable-diffusion","terminationGracePeriodSeconds":30}},"updateStrategy":{"rollingUpdate":{"partition":0},"type":"RollingUpdate"},"volumeClaimTemplates":[{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"creationTimestamp":null,"name":"sd-stable-diffusion-model-store"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"rook-ceph-block","volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]},"status":{"availableReplicas":0,"collisionCount":0,"currentReplicas":1,"currentRevision":"sd-stable-diffusion-567bbd5b58","observedGeneration":2,"replicas":1,"updateRevision":"sd-stable-diffusion-674965c49"}}
    meta.helm.sh/release-name: sd
    meta.helm.sh/release-namespace: ordingj
  creationTimestamp: "2025-11-25T02:25:02Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: sd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stable-diffusion
    app.kubernetes.io/version: 1.4.0
    helm.sh/chart: stable-diffusion-1.0.6
  name: sd-stable-diffusion
  namespace: ordingj
  resourceVersion: "11963701897"
  uid: 5e38ee1f-98ff-4e18-9134-7f5d284bee63
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: sd
      app.kubernetes.io/name: stable-diffusion
  serviceName: sd-stable-diffusion
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sd
        app.kubernetes.io/name: stable-diffusion
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: sd-stable-diffusion-config
          image: amithkk/stable-diffusion:latest
          imagePullPolicy: IfNotPresent
          name: stable-diffusion-stable-diffusion
          ports:
            - containerPort: 7860
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 8Gi
              nvidia.com/gpu: "1"
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /models
              name: sd-stable-diffusion-model-store
      dnsPolicy: ClusterFirst
      initContainers:
        - name: ensure-stable-models
          image: curlimages/curl:8.10.1
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -e
              mkdir -p /models

              echo "Downloading Stable Diffusion 1.4..."
              curl -L "https://f004.backblazeb2.com/file/aai-blog-files/sd-v1-4.ckpt" -o /models/model.ckpt

              echo "Downloading GFPGAN..."
              curl -L "https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth" -o /models/GFPGANv1.3.pth

              echo "Downloading RealESRGAN models..."
              curl -L "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth" -o /models/RealESRGAN_x4plus.pth
              curl -L "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth" -o /models/RealESRGAN_x4plus_anime_6B.pth
          imagePullPolicy: IfNotPresent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /models
              name: sd-stable-diffusion-model-store
      nodeSelector:
        nvidia.com/gpu.present: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sd-stable-diffusion
      serviceAccountName: sd-stable-diffusion
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: sd-stable-diffusion-model-store
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-ceph-block
        volumeMode: Filesystem
      status:
        phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentRevision: sd-stable-diffusion-567bbd5b58
  observedGeneration: 3
  replicas: 1
  updateRevision: sd-stable-diffusion-5587cdb995
  updatedReplicas: 1
