apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
    - name: gpu-container
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: 1
